version: 2.0

defaults: &defaults
  working_directory: /go/src/github.com/gochain-io/chainload
  docker:
      - image: circleci/golang:1.13
  environment: # apparently expansion doesn't work here yet: https://discuss.circleci.com/t/environment-variable-expansion-in-working-directory/11322
    - OS=linux
    - ARCH=amd64

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: make build
      - run: make test
  release:
    <<: *defaults
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run:
          name: install gcloud
          command: |
            wget https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-204.0.0-linux-x86_64.tar.gz --directory-prefix=tmp
            tar -xvzf tmp/google-cloud-sdk-204.0.0-linux-x86_64.tar.gz -C tmp
            ./tmp/google-cloud-sdk/install.sh -q
      - deploy:
          command: |
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            echo $GOOGLE_AUTH | docker login -u _json_key --password-stdin https://gcr.io
            echo $GOOGLE_AUTH > ${HOME}/gcloud-service-key.json
            make release

workflows:
  version: 2
  build-release:
    jobs:
      - build

      - approve-release:
          type: approval
          requires:
            - build

      - release:
          requires:
            - approve-release