version: 2
jobs:
  build:
    machine: true
    working_directory: ~/go/src/github.com/gochain-io/chainload
    environment: # apparently expansion doesn't work here yet: https://discuss.circleci.com/t/environment-variable-expansion-in-working-directory/11322
      - GOPATH=/home/circleci/go
      - GOVERSION=1.12
      - GO111MODULE=on
      - OS=linux
      - ARCH=amd64
    steps:
      - checkout
      - run:
          name: update Go
          command: |
            go version
            go env GOROOT
            mkdir tmp
            cd tmp
            sudo rm -rf /usr/local/go
            wget https://storage.googleapis.com/golang/go$GOVERSION.$OS-$ARCH.tar.gz
            sudo tar -C /usr/local -xzf go$GOVERSION.$OS-$ARCH.tar.gz
            export PATH=$PATH:$HOME/go/bin
      - run: go version
      - run:
          name: update Docker
          command: |
            docker version
            sudo service docker stop
            curl -fsSL https://get.docker.com/ | sudo sh
      - run: docker version
      - run: make test
      - run: make docker
      - run:
          name: install gcloud
          command: |
            wget https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-204.0.0-linux-x86_64.tar.gz --directory-prefix=tmp
            tar -xvzf tmp/google-cloud-sdk-204.0.0-linux-x86_64.tar.gz -C tmp
            ./tmp/google-cloud-sdk/install.sh -q
      - deploy:
          command: |
            if [[ "${CIRCLE_BRANCH}" == "master" && -z "${CIRCLE_PR_REPONAME}" ]]; then
              git config --global user.email "ci@gochain.io"
              git config --global user.name "CI"
              git branch --set-upstream-to=origin/${CIRCLE_BRANCH} ${CIRCLE_BRANCH}
              echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
              echo $GOOGLE_AUTH | docker login -u _json_key --password-stdin https://gcr.io
              echo $GOOGLE_AUTH > ${HOME}/gcloud-service-key.json
              make release
            fi
